version: "3.1"

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DBNAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./docker/data:/var/lib/mysql
      - ./docker/socket:/run/mysqld

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile 
    restart: always
    volumes:
      - ./app:/usr/src/app
      - ./docker/socket:/run/mysqld
    ports: 
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mariadb

