# Generated by Django 5.0.3 on 2024-03-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_shift_assigned_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-start_at', '-end_at']},
        ),
        migrations.AddField(
            model_name='user',
            name='calendar_place',
            field=models.IntegerField(default=0),
        ),
    ]
